import type { Metadata } from "next";
import DefaultPage from "./global/DefaultPage";
import RootLayoutClient from "./styles/RootLayoutClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RootLayoutClient>
          <DefaultPage>{children}</DefaultPage>
        </RootLayoutClient>
      </body>
    </html>
  );
}
